# Permalinks
permalink:           pretty

# Setup
title:               Tamas Abraham
tagline:             The Growth & DevRel guy
url:                 http://getpoole.com
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Tamas Abraham
  url:               https://twitter.com/tamasabraham
  email:             tombbram@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/poole/poole

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-gist
